// Code generated by github.com/dashotv/golem. DO NOT EDIT.
package app

import (
	"time"

	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.uber.org/zap"

	"github.com/dashotv/grimoire"
)

func init() {
	initializers = append(initializers, setupDb)
	healthchecks["db"] = checkDb
}

func setupDb(app *Application) error {
	db, err := NewConnector(app)
	if err != nil {
		return err
	}

	app.DB = db
	return nil
}

func checkDb(app *Application) (err error) {
	// TODO: Check DB connection
	return nil
}

type Connector struct {
	Log   *zap.SugaredLogger
	Page  *grimoire.Store[*Page]
	Video *grimoire.Store[*Video]
	Visit *grimoire.Store[*Visit]
}

func NewConnector(app *Application) (*Connector, error) {
	var s *Connection
	var err error

	s, err = app.Config.ConnectionFor("page")
	if err != nil {
		return nil, err
	}
	page, err := grimoire.New[*Page](s.URI, s.Database, s.Collection)
	if err != nil {
		return nil, err
	}

	s, err = app.Config.ConnectionFor("video")
	if err != nil {
		return nil, err
	}
	video, err := grimoire.New[*Video](s.URI, s.Database, s.Collection)
	if err != nil {
		return nil, err
	}

	s, err = app.Config.ConnectionFor("visit")
	if err != nil {
		return nil, err
	}
	visit, err := grimoire.New[*Visit](s.URI, s.Database, s.Collection)
	if err != nil {
		return nil, err
	}

	c := &Connector{
		Log:   app.Log.Named("db"),
		Page:  page,
		Video: video,
		Visit: visit,
	}

	return c, nil
}

type Page struct { // model
	grimoire.Document `bson:",inline"` // includes default model settings
	//ID        primitive.ObjectID `bson:"_id,omitempty" json:"id"`
	//CreatedAt time.Time          `bson:"created_at" json:"created_at"`
	//UpdatedAt time.Time          `bson:"updated_at" json:"updated_at"`
	Name        string    `bson:"name" json:"name"`
	Url         string    `bson:"url" json:"url"`
	Scraper     string    `bson:"scraper" json:"scraper"`
	Downloader  string    `bson:"downloader" json:"downloader"`
	ProcessedAt time.Time `bson:"processed_at" json:"processed_at"`
}

type Video struct { // model
	grimoire.Document `bson:",inline"` // includes default model settings
	//ID        primitive.ObjectID `bson:"_id,omitempty" json:"id"`
	//CreatedAt time.Time          `bson:"created_at" json:"created_at"`
	//UpdatedAt time.Time          `bson:"updated_at" json:"updated_at"`
	Title      string `bson:"title" json:"title"`
	Season     int    `bson:"season" json:"season"`
	Episode    int    `bson:"episode" json:"episode"`
	Raw        string `bson:"raw" json:"raw"`
	DisplayId  string `bson:"display_id" json:"display_id"`
	Extension  string `bson:"extension" json:"extension"`
	Resolution int    `bson:"resolution" json:"resolution"`
	Size       int64  `bson:"size" json:"size"`
	Download   string `bson:"download" json:"download"`
	View       string `bson:"view" json:"view"`
	Source     string `bson:"source" json:"source"`
}

type Visit struct { // model
	grimoire.Document `bson:",inline"` // includes default model settings
	//ID        primitive.ObjectID `bson:"_id,omitempty" json:"id"`
	//CreatedAt time.Time          `bson:"created_at" json:"created_at"`
	//UpdatedAt time.Time          `bson:"updated_at" json:"updated_at"`
	PageId primitive.ObjectID `bson:"page_id" json:"page_id"`
	Url    string             `bson:"url" json:"url"`
}
