version: 0.14.2
name: rift
repo: github.com/dashotv/rift
package: app
output: internal/app
plugins:
  models: true
  routes: true
  workers: true
  cache: false
  events: true
  clients: true
definitions:
  models: .golem/models
  routes: .golem/routes
  events: .golem/events
  workers: .golem/workers
  queues: .golem/queues
  clients: .golem/clients
